INFO:root:Loading data...
    DATABASE: data\02_stg\stg_disaster_response.db
INFO:root:Loading data...
    DATABASE: data\02_stg\stg_disaster_response.db
INFO:root:Building model...
INFO:root:Training model...
INFO:root:Evaluating model...
INFO:root:Saving model...
    MODEL: classifier.pkl
INFO:root:Trained model saved!
2024-04-03 11:10:18,895 [MainThread  ] [INFO ]  Loading data...
    DATABASE: data\02_stg\stg_disaster_response.db
2024-04-03 11:10:19,181 [MainThread  ] [INFO ]  Building model...
2024-04-03 11:10:19,181 [MainThread  ] [INFO ]  Training model...
2024-04-03 11:11:48,017 [MainThread  ] [INFO ]  Evaluating model...
2024-04-03 11:11:51,637 [MainThread  ] [INFO ]  Saving model...
    MODEL: classifier.pkl
2024-04-03 11:11:52,991 [MainThread  ] [INFO ]  Trained model saved!
2024-04-03 11:44:54,683 [MainThread  ] [ERROR]  Please provide the filepaths of the messages and categories datasets as the first and second argument respectively, as well as the filepath of the database to save the cleaned data to as the third argument. 

Example: python process_data.py disaster_messages.csv disaster_categories.csv DisasterResponse.db
2024-04-03 11:45:11,972 [MainThread  ] [ERROR]  Please provide the filepaths of the messages and categories datasets as the first and second argument respectively, as well as the filepath of the database to save the cleaned data to as the third argument. 

Example: python process_data.py disaster_messages.csv disaster_categories.csv DisasterResponse.db
2024-04-03 11:46:00,581 [MainThread  ] [ERROR]  Please provide the filepaths of the messages and categories datasets as the first and second argument respectively, as well as the filepath of the database to save the cleaned data to as the third argument. 

Example: python process_data.py disaster_messages.csv disaster_categories.csv DisasterResponse.db
2024-04-03 11:47:18,898 [MainThread  ] [INFO ]  Loading data...
    MESSAGES: data\01_raw\disaster_categories.csv
    CATEGORIES: data\01_raw\disaster_messages.csv
2024-04-03 11:47:19,077 [MainThread  ] [INFO ]  Cleaning data...
2024-04-03 11:47:19,626 [MainThread  ] [INFO ]  Saving data...
    DATABASE: data\02_stg\stg_disaster_response.db
2024-04-03 11:52:33,462 [MainThread  ] [ERROR]  Error loading data: [Errno 22] Invalid argument: 'data\x01_raw\\disaster_messages.csv'
2024-04-03 11:54:24,127 [MainThread  ] [ERROR]  Please provide the filepaths of the messages and categories datasets as the first and second argument respectively, as well as the filepath of the database to save the cleaned data to as the third argument. 

Example: python process_data.py disaster_messages.csv disaster_categories.csv DisasterResponse.db
2024-04-03 11:55:11,952 [MainThread  ] [ERROR]  Please provide the filepaths of the messages and categories datasets as the first and second argument respectively, as well as the filepath of the database to save the cleaned data to as the third argument. 

Example: python process_data.py disaster_messages.csv disaster_categories.csv DisasterResponse.db
2024-04-03 11:55:50,304 [MainThread  ] [INFO ]  Loading data...
    MESSAGES: C:\Users\grant\OneDrive\Documents\udacity_data_science_program\05_disaster_response_project\data\01_raw\disaster_messages.csv
    CATEGORIES: C:\Users\grant\OneDrive\Documents\udacity_data_science_program\05_disaster_response_project\data\01_raw\disaster_categories.csv
2024-04-03 11:55:50,412 [MainThread  ] [INFO ]  Cleaning data...
2024-04-03 11:55:50,960 [MainThread  ] [INFO ]  Saving data...
    DATABASE: C:\Users\grant\OneDrive\Documents\udacity_data_science_program\05_disaster_response_project\data\02_stg\stg_disaster_response.db
2024-04-03 11:59:45,894 [MainThread  ] [INFO ]  Loading data...
    MESSAGES: C:\Users\grant\OneDrive\Documents\udacity_data_science_program\05_disaster_response_project\data\01_raw\disaster_messages.csv
    CATEGORIES: C:\Users\grant\OneDrive\Documents\udacity_data_science_program\05_disaster_response_project\data\01_raw\disaster_categories.csv
2024-04-03 11:59:46,019 [MainThread  ] [INFO ]  Cleaning data...
2024-04-03 11:59:46,530 [MainThread  ] [INFO ]  Saving data...
    DATABASE: C:\Users\grant\OneDrive\Documents\udacity_data_science_program\05_disaster_response_project\data\02_stg\stg_disaster_response.db
2024-04-03 11:59:46,936 [MainThread  ] [INFO ]  Cleaned data saved to database!
